### ISSUE TITLE
Pod stuck in `ContainerCreating` state in k8 1.12.3

### ISSUE THREAD

**Issue by surbhibakhtiyar** [dims/docker-flexvol#6]
While creating pod using this driver it gives the following error :
```
  Warning  FailedMount  6s (x5 over 14s)  kubelet, 10.xx.xx.xx  MountVolume.SetUp failed for volume "test" : invalid character '/' looking for beginning of value
```

The same script `docker-flexvol.sh` works fine with k8 `1.10.11` but not `1.12.3`

**Comment by surbhibakhtiyar** [comment]
@dims ^^

**Comment by dims** [comment]
@surbhibakhtiyar i tried the steps outlined in README.md against latest kubernetes and i don't see the issue. Can you please try the exact same steps as in the readme including the `my-container-image` container and let me know please?

**Comment by surbhibakhtiyar** [comment]
@dims  I tried the exact same steps as in the readme including the my-container-image container but it didn't work for me. It gives same error
```
apiVersion: v1
kind: Pod
metadata:
  name: nginx
  namespace: testNamespace
spec:
  containers:
  - name: nginx
    image: nginx
    volumeMounts:
    - name: test
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: test
    flexVolume:
      driver: "dims.io/docker-flexvol"
      options:
        image: "registry.ng.bluemix.net/test/my-container-image"
        name: "/data-store"
  imagePullSecrets:
  - name: mysecret
  nodeSelector: 
    kubernetes.io/hostname: xxxx
  
```

Error:
```
Events:
  Type     Reason       Age               From                   Message
  ----     ------       ----              ----                   -------
  Normal   Scheduled    12s               default-scheduler      Successfully assigned testNamespace/nginx to 10.xx.xx.xxx
  Warning  FailedMount  4s (x5 over 12s)  kubelet, 10.xx.xx.xxx  MountVolume.SetUp failed for volume "test" : invalid character '/' looking for beginning of value
```
